package com.file.cleaner.constants;

public enum FILE_ATTRIBUTES {
	NAME,
	EXTENSION,
	SIZE,
	IS_FILE,
	IS_DIRECTORY,
	IS_DIRECTORY_EMPTY,
	CREATION_MINUTES_AGE,
	CREATION_HOURS_AGE,
	CREATION_DAYS_AGE,
	CREATION_WEEKS_AGE,
	CREATION_MONTHS_AGE,
	CREATION_YEARS_AGE,
	MODIFIED_MINUTES_AGE,
	MODIFIED_HOURS_AGE,
	MODIFIED_DAYS_AGE,
	MODIFIED_WEEKS_AGE,
	MODIFIED_MONTHS_AGE,
	MODIFIED_YEARS_AGE,
	NAME_EXPRESSION_MINUTES_AGE,
	NAME_EXPRESSION_HOURS_AGE,
	NAME_EXPRESSION_DAYS_AGE,
	NAME_EXPRESSION_WEEKS_AGE,
	NAME_EXPRESSION_MONTHS_AGE,
	NAME_EXPRESSION_YEARS_AGE;
}
